### ISSUE TITLE
Constructor error

### ISSUE THREAD

**Issue by zeichenkette** [onuryilmaz/turkish-pos-tagger#3]
Importing the pos_tagger module throws an error when it tries to access the pre-trained data in the yaml file:

``---------------------------------------------------------------------------
ConstructorError                          Traceback (most recent call last)
<ipython-input-1-bed576962de1> in <module>()
----> 1 import pos_tagger

/home/kuhn/repos/github/turkish-pos-tagger/pos_tagger.py in <module>()
     20 # Open the file where tagger is saved
     21 f=open('my_tagger.yaml')
---> 22 myTagger=yaml.load(f)
     23 
     24 # Tagger function

/home/kuhn/Applications/anaconda2/lib/python2.7/site-packages/yaml/**init**.pyc in load(stream, Loader)
     69     loader = Loader(stream)
     70     try:
---> 71         return loader.get_single_data()
     72     finally:
     73         loader.dispose()

/home/kuhn/Applications/anaconda2/lib/python2.7/site-packages/yaml/constructor.pyc in get_single_data(self)
     37         node = self.get_single_node()
     38         if node is not None:
---> 39             return self.construct_document(node)
     40         return None
     41 

/home/kuhn/Applications/anaconda2/lib/python2.7/site-packages/yaml/constructor.pyc in construct_document(self, node)
     41 
     42     def construct_document(self, node):
---> 43         data = self.construct_object(node)
     44         while self.state_generators:
     45             state_generators = self.state_generators

/home/kuhn/Applications/anaconda2/lib/python2.7/site-packages/yaml/constructor.pyc in construct_object(self, node, deep)
     86                     constructor = self.**class**.construct_mapping
     87         if tag_suffix is None:
---> 88             data = constructor(self, node)
     89         else:
     90             data = constructor(self, tag_suffix, node)

/home/kuhn/Applications/anaconda2/lib/python2.7/site-packages/yaml/constructor.pyc in construct_undefined(self, node)
    412         raise ConstructorError(None, None,
    413                 "could not determine a constructor for the tag %r" % node.tag.encode('utf-8'),
--> 414                 node.start_mark)
    415 
    416 SafeConstructor.add_constructor(

ConstructorError: could not determine a constructor for the tag '!nltk.BrillTagger'
  in "my_tagger.yaml", line 1, column 1
``

**Comment by onuryilmaz** [comment]
I am currently able to work with the following versions:
nltk @ 2.0.5
PyYAML @ 3.12

I have also updated the documentation: https://github.com/onuryilmaz/turkish-pos-tagger/blob/master/README.md

**Comment by ahmettmertt** [comment]
I have the same issue, even i have nltk 2.0.5 and pyyaml 3.12 my python version is 2.7.12 but i don't think thats the problem. How can i solve this?

**Comment by onuryilmaz** [comment]
With the Dockerfile provided, I guess the issue should be solved:
https://github.com/onuryilmaz/turkish-pos-tagger/blob/master/README.md#build-and-run-using-docker
