### ISSUE TITLE
Wrong Tagging for words

### ISSUE THREAD

**Issue by Mica7812** [onuryilmaz/turkish-pos-tagger#5]
I have tried the program. However, when I tried a simple sentence as such

>>> tag("Sezonunun 5. Bölümü hakkında konuşmak istiyorum.")
[('Sezonunun', 'Noun_Nom'), ('5.', 'Noun_Nom'), ('B\xc3\xb6l\xc3\xbcm\xc3\xbc', 'Noun_Nom'), ('hakk\xc4\xb1nda', 'Noun_Nom'), ('konu\xc5\x9fmak', 'Noun_Nom'), ('istiyorum.', 'Noun_Nom')]

The program recognizes the verbs as nouns. How come?

Do I have to train the program somehow? How am I supposed to do that?

Also the program only seems to work with Dockerfile. As a result I can only run via a terminal. How can I use the program by using in other python files?

**Comment by zeichenkette** [comment]
> Also the program only seems to work with Dockerfile. As a result I can only run via a terminal. How can I use the program by using in other python files?

The nltk version used in the Dockerfile is slightly old but the last one the tagger works with. To get it running without docker, you should use a custom python environment. Its easy to set up using anaconda.
